/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATM;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dev
 */
public class NewAccount extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form NewAccount
     */
    public NewAccount() {
        super("HomePage");
        initComponents();
        conn = JavaConnect.ConncerDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        Create = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        security = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ammount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(211, 84, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("1942 report", 1, 36)); // NOI18N
        jLabel1.setText("ATM Booth");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ATM/ATM.PNG"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 222, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 510));

        jPanel5.setBackground(new java.awt.Color(108, 122, 137));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("1942 report", 1, 24)); // NOI18N
        jLabel2.setText("Wellcome to Our ATM Booth");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(67, 57, 425, 25);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("First Name :");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(120, 120, 76, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Last Name :");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(120, 160, 75, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Security Ques :");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(100, 200, 97, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Password :");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(130, 330, 69, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Confirm Password :");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(80, 370, 122, 19);
        jPanel5.add(first);
        first.setBounds(220, 120, 197, 30);

        last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastActionPerformed(evt);
            }
        });
        jPanel5.add(last);
        last.setBounds(220, 160, 197, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your phone number?", "What is your pet name?", "Last four digit of your old phone number?", "What is your old home town?" }));
        jPanel5.add(jComboBox1);
        jComboBox1.setBounds(220, 200, 197, 30);
        jPanel5.add(password);
        password.setBounds(220, 320, 197, 30);
        jPanel5.add(jPasswordField2);
        jPasswordField2.setBounds(220, 360, 197, 30);

        Create.setBackground(new java.awt.Color(38, 194, 129));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });
        jPanel5.add(Create);
        Create.setBounds(240, 460, 73, 25);

        Back.setBackground(new java.awt.Color(255, 0, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel5.add(Back);
        Back.setBounds(330, 460, 58, 25);

        jCheckBox1.setText("I read all term and privecy.");
        jPanel5.add(jCheckBox1);
        jCheckBox1.setBounds(220, 410, 210, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Answer :");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(140, 240, 70, 19);
        jPanel5.add(security);
        security.setBounds(220, 240, 200, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Ammount :");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(130, 280, 70, 19);

        ammount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammountActionPerformed(evt);
            }
        });
        jPanel5.add(ammount);
        ammount.setBounds(220, 280, 200, 30);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 570, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Insert into Database (First,Last,Security,Ammount,Password) values (?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, first.getText());
            pst.setString(2, last.getText());
            pst.setString(3, security.getText());
            pst.setString(4, password.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null, "Create new Account success");
            rs.close();
            pst.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        int balance = Integer.parseInt(this.ammount.getText());
        JOptionPane.showMessageDialog(this.ammount, "You have successfully create new account of our booth..\n Thanks ..!!");

    }//GEN-LAST:event_CreateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed


    private void lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastActionPerformed

    private void ammountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammountActionPerformed
        // TODO add your handling code here:
        Check c = new Check();
        Check.ammountcheck.setText(this.ammount.getText());
        c.setVisible(true);
    }//GEN-LAST:event_ammountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Create;
    private javax.swing.JTextField ammount;
    private javax.swing.JTextField first;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField last;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField security;
    // End of variables declaration//GEN-END:variables
}
